import {useEffect, useState} from 'react';
import {api} from '../services/api';
import {useLoad} from '../hooks/useLoad';
import type {Comparison as ComparisonResult, Experiment, MetricName} from '../types';
import {Card, ConfusionMatrix, Empty, ErrorNotice, Field, JsonView, MetricGrid, Note, PageHeader, Status} from '../components/Common';
import {ROCChart} from '../components/Charts';
import {metric, modelLabels, seconds, shortId} from '../utils/format';
export default function Comparison() {
  const list = useLoad(() => api.get<Experiment[]>('/experiments')); const [id, setId] = useState(''); const [modelId, setModelId] = useState('');
  useEffect(() => {if (!id && list.data?.length) setId(list.data[0].id);}, [list.data, id]);
  const result = useLoad<ComparisonResult | null>(() => id ? api.get(`/experiments/${id}/comparison`) : Promise.resolve(null), [id], 5000);
  const ready = result.data?.models.filter(m => m.status === 'ready') || [];
  const selected = ready.find(m => m.id === modelId) || ready[0];
  const names: MetricName[] = ['sensitivity', 'specificity', 'roc_auc', 'f1', 'accuracy', 'precision', 'recall'];
  const curves = ready.flatMap(m => m.metrics.test?.roc_curve ? [{name: modelLabels[m.model_type], ...m.metrics.test.roc_curve}] : []);
  return <><PageHeader eyebrow="07 / Balanced benchmarking" title="Let the measured result lead." description="Sensitivity, specificity, false negatives, generalization and cost stay visible even when a quantum model performs worse."/><ErrorNotice message={list.error || result.error}/><Field label="Experiment with shared comparison conditions"><select value={id} onChange={e => {setId(e.target.value); setModelId('');}}><option value="">Select experiment</option>{list.data?.map(e => <option key={e.id} value={e.id}>{shortId(e.id)} / {e.status}</option>)}</select></Field>
    {result.data && <><Note>{result.data.conclusion}</Note><Card title="Held-out test performance"><div className="table-scroll"><table><thead><tr><th>Model</th><th>Status</th>{names.map(n => <th key={n}>{n.replace('_', '-')}</th>)}<th>Final train time</th><th>CV total time</th><th>Inference / sample</th></tr></thead><tbody>{result.data.models.map(m => <tr key={m.id}><td><button className="text-button" onClick={() => setModelId(m.id)}>{modelLabels[m.model_type]}</button></td><td><Status value={m.status}/></td>{names.map(n => <td key={n}>{metric(m.metrics.test?.[n], n !== 'roc_auc')}</td>)}<td>{seconds(m.metrics.timing?.final_training_seconds)}</td><td>{seconds(m.metrics.timing?.cv_total_seconds)}</td><td>{seconds(m.metrics.timing?.test_inference_seconds_per_sample)}</td></tr>)}</tbody></table></div>{!result.data.models.length && <Empty>No model has finished; completed and failed models will both be shown here.</Empty>}</Card>
    {selected?.metrics.test && <><Card title={`${modelLabels[selected.model_type]} / held-out metrics`}><MetricGrid metrics={selected.metrics.test}/></Card><div className="two-columns"><Card title="False positives and false negatives"><ConfusionMatrix metrics={selected.metrics.test}/></Card><Card title="ROC comparison"><ROCChart curves={curves}/></Card></div><Card title="Generalization: CV mean and standard deviation"><div className="table-scroll"><table><thead><tr><th>Metric</th><th>Training (resubstitution)</th><th>CV mean</th><th>CV sample SD</th><th>Held-out test</th></tr></thead><tbody>{names.map(n => <tr key={n}><td>{n}</td><td>{metric(selected.metrics.training?.[n], n !== 'roc_auc')}</td><td>{metric(selected.metrics.validation?.summary[n].mean, n !== 'roc_auc')}</td><td>{metric(selected.metrics.validation?.summary[n].std, n !== 'roc_auc')}</td><td>{metric(selected.metrics.test?.[n], n !== 'roc_auc')}</td></tr>)}</tbody></table></div><p>CV dispersion is not a confidence interval. Training performance is not evidence of real-world clinical performance.</p><JsonView value={selected.metrics.calibration} label="Separate probability calibration diagnostics"/></Card></>}
    <Card title="Classical-quantum pairwise interpretation">{result.data.pairs.length ? result.data.pairs.map((pair, i) => <div className="pair-summary" key={i}><h3>{pair.quantum_type.toUpperCase()} vs {pair.classical_type}</h3><p>{pair.conclusion}</p><JsonView value={pair} label="All metric differences and measured time difference"/></div>) : <Empty>A completed classical model and a completed quantum model are needed for a pairwise conclusion.</Empty>}<JsonView value={{split: result.data.split, fingerprint: result.data.comparison_fingerprint, limitations: result.data.limitations}} label="Comparison conditions and limitations"/></Card></>}</>;
}
