import {Link} from 'react-router-dom';
import {api} from '../services/api';
import {useLoad} from '../hooks/useLoad';
import type {Experiment} from '../types';
import {Card, Empty, ErrorNotice, PageHeader, Status} from '../components/Common';
import {dateTime, shortId} from '../utils/format';
export default function Dashboard() {
  const {data, error} = useLoad(() => api.get<{counts: Record<string, number>; recent_experiments: Experiment[]}>('/summary'), [], 7000);
  return <><PageHeader eyebrow="Biomedical research workspace" title="Evidence before advantage." description="Process biomedical features, compare classical and quantum models, and keep every conclusion traceable to a measured experiment."><Link className="button" to="/datasets">Begin with a dataset</Link></PageHeader><ErrorNotice message={error}/>
    <div className="hero-panel"><div><span className="pill">HYBRID QUANTUM-CLASSICAL ML</span><h2>A transparent path from data to research prediction.</h2><p>Shared partitions. Training-only transformations. Visible false negatives. No diagnosis claims.</p><div className="workflow-ribbon">Validate <span>/</span> Prepare <span>/</span> Train <span>/</span> Explain <span>/</span> Compare</div></div><svg className="orbit" viewBox="0 0 220 220" aria-hidden="true"><ellipse cx="110" cy="110" rx="90" ry="36" transform="rotate(45 110 110)"/><ellipse cx="110" cy="110" rx="90" ry="36" transform="rotate(-45 110 110)"/><circle cx="110" cy="110" r="14"/><circle cx="171" cy="171" r="7"/></svg></div>
    <div className="stat-grid">{[['datasets', 'Datasets'], ['experiments', 'Experiments'], ['ready_models', 'Registered models'], ['active_jobs', 'Active jobs']].map(([key, label]) => <Card key={key}><p className="eyebrow">{label}</p><strong className="stat-number">{data?.counts[key] ?? '\u2014'}</strong><small>From this workspace</small></Card>)}</div>
    <div className="two-columns"><Card title="Recent experiments">{data?.recent_experiments.length ? <div className="record-list">{data.recent_experiments.map(e => <Link to={`/experiments/${e.id}`} key={e.id}><div><strong>{shortId(e.id)}</strong><small>{dateTime(e.created_at)}</small></div><Status value={e.status}/></Link>)}</div> : <Empty>No experimental results yet. Load the public benchmark and run the training workflow; all displayed metrics will be calculated at runtime.</Empty>}</Card><Card title="Research boundaries"><h3>Prediction is not diagnosis.</h3><p>Classifier scores are model outputs, not clinically validated individual risk. The Wisconsin benchmark demonstrates a methodology, not a screening device.</p><h3>Simulation is not hardware.</h3><p>VQC and QSVC run on local simulators. A favorable metric alone does not establish general quantum advantage.</p><Link to="/comparison" className="text-link">Review the comparison workspace</Link></Card></div></>;
}
