import {Link, useParams} from 'react-router-dom';
import {api} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import type {ExperimentDetail as Detail} from '../types';
import {Card, ConfusionMatrix, Empty, ErrorNotice, JsonView, MetricGrid, Note, PageHeader, Status} from '../components/Common';
import {dateTime, modelLabels, seconds, shortId} from '../utils/format';
export default function ExperimentDetail() {
  const {id = ''} = useParams(); const result = useLoad(() => api.get<Detail>(`/experiments/${id}`), [id], 5000); const action = useAction();
  return <><PageHeader eyebrow="12 / Experiment evidence" title={`Experiment ${shortId(id)}`} description="Inspect the complete configuration, model registry entries, measured evaluation and provenance behind this experiment."><Link className="button secondary" to="/experiments">All experiments</Link></PageHeader><ErrorNotice message={result.error || action.error}/>
    {result.data && <><div className="action-bar"><Status value={result.data.experiment.status}/><span>{dateTime(result.data.experiment.created_at)}</span><button disabled={action.busy} onClick={() => void action.run(() => api.download(`/experiments/${id}/report?format=html`, `qhealth-${id}.html`))}>Export HTML research report</button><button className="secondary" disabled={action.busy} onClick={() => void action.run(() => api.download(`/experiments/${id}/report?format=json`, `qhealth-${id}.json`))}>Export JSON report</button></div>
    <Note>Reports include the medical disclaimer, dataset provenance, measured metrics, computational measurements, available explanations, limitations and result-dependent conclusions. Uncomputed values are not fabricated.</Note><div className="two-columns"><Card title="Provenance and partition record"><JsonView value={result.data.experiment.summary} label="Dataset, hash, split, versions and limitations"/>{result.data.experiment.parent_id && <Link to={`/experiments/${result.data.experiment.parent_id}`}>Open parent experiment</Link>}</Card><Card title="Exact experiment configuration"><JsonView value={result.data.experiment.config} label="All training and quantum settings"/>{result.data.jobs.map(j => <div key={j.id}><Status value={j.status}/><p>{j.state}</p><progress value={j.progress} max={100}/><JsonView value={j.errors} label="Job failure records"/></div>)}</Card></div>
    {result.data.models.length ? result.data.models.map(model => <Card key={model.id} title={`${modelLabels[model.model_type]} / model ${shortId(model.id)}`}><Status value={model.status}/>{model.metrics.test ? <><MetricGrid metrics={model.metrics.test}/><ConfusionMatrix metrics={model.metrics.test}/><p>Final training: {seconds(model.metrics.timing?.final_training_seconds)}. Full cross-validation: {seconds(model.metrics.timing?.cv_total_seconds)}. Test inference: {seconds(model.metrics.timing?.test_inference_seconds)}.</p><JsonView value={model.metrics.validation} label="Cross-validation folds, mean and sample standard deviation"/><JsonView value={model.metrics.training} label="Training resubstitution performance (not validation)"/><JsonView value={model.metrics.calibration} label="Probability calibration diagnostics"/></> : <Empty>This model has no completed measurements.</Empty>}<JsonView value={model.details} label="Model identity, provenance, preprocessing, quantum configuration and limitations"/></Card>) : <Empty>Model records appear after training finishes or a model failure is recorded.</Empty>}</>}</>;
}
