import {useState} from 'react';
import {api} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import type {Explanation, ModelRecord} from '../types';
import {Card, Empty, ErrorNotice, Field, JsonView, ModelPicker, Note, PageHeader} from '../components/Common';
import {BarChart} from '../components/Charts';
import {dateTime, seconds} from '../utils/format';
export default function Explainability() {
  const [id, setId] = useState(''); const [method, setMethod] = useState('permutation'); const [samples, setSamples] = useState(8); const [repeats, setRepeats] = useState(3); const [maxFeatures, setMaxFeatures] = useState(30);
  const action = useAction(); const model = useLoad<ModelRecord | null>(() => id ? api.get(`/models/${id}`) : Promise.resolve(null), [id]);
  const explanations = useLoad<Explanation[]>(() => id ? api.get(`/models/${id}/explanations`) : Promise.resolve([]), [id]);
  const [selected, setSelected] = useState<Explanation>(); const quantum = ['vqc', 'qsvc'].includes(model.data?.model_type || ''); const activeMethod = quantum ? 'perturbation' : method;
  const current = selected?.model_id === id ? selected : explanations.data?.[0];
  async function run() {const value = await action.run(() => api.post<Explanation>(`/models/${id}/explain`, {method: activeMethod, max_samples: samples, repeats, max_features: maxFeatures})); if (value) {setSelected(value); explanations.reload();}}
  return <><PageHeader eyebrow="09 / Model feature influence" title="Explain influence, not medical cause." description="Compute bounded post-hoc explanations for a frozen model. Explanations do not feed back into training or justify clinical decisions."/><ModelPicker value={id} onChange={setId}/><ErrorNotice message={action.error || model.error || explanations.error}/>
    <Card title="Explanation method"><div className="form-grid"><Field label="Method"><select value={activeMethod} disabled={quantum} onChange={e => setMethod(e.target.value)}><option value="permutation">Permutation importance / ROC-AUC decrease</option><option value="shap">Approximate SHAP / numeric-only complete inputs</option><option value="perturbation">Feature perturbation / sensitivity analysis</option></select></Field><Field label="Maximum held-out samples"><input type="number" min={2} max={32} value={samples} onChange={e => setSamples(Number(e.target.value))}/></Field><Field label="Permutation / SHAP repeats"><input type="number" min={1} max={10} disabled={activeMethod === 'perturbation'} value={repeats} onChange={e => setRepeats(Number(e.target.value))}/></Field><Field label="Maximum perturbed features"><input type="number" min={1} max={60} disabled={activeMethod !== 'perturbation'} value={maxFeatures} onChange={e => setMaxFeatures(Number(e.target.value))}/></Field></div><Note>{quantum ? 'Quantum explanation uses observed prediction changes under feature perturbation. It is not a complete interpretation of circuit internals.' : 'Training-only background data is used. Correlation, off-manifold perturbations and small explanation subsets limit interpretation.'}</Note><button disabled={!id || action.busy} onClick={() => void run()}>{action.busy ? 'Calculating feature influence...' : 'Calculate explanation'}</button></Card>
    {current ? <Card title={current.result.title}><p>{current.result.scope}</p><p>{current.result.sample_count} explained samples / {seconds(current.result.elapsed_seconds)} / {dateTime(current.created_at)}</p><p>{current.result.units}</p><BarChart label="Measured model feature influence" items={current.result.influence.slice(0, 30).map(i => ({name: i.feature, value: i.magnitude}))}/><JsonView value={current.result} label="Full measured influence and limitations"/></Card> : <Empty>No explanation has been calculated for this model.</Empty>}</>;
}
