import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {Card, DatasetPicker, ErrorNotice, Field, Note, PageHeader} from '../components/Common';
import {BarChart} from '../components/Charts';
import type {PipelineConfig} from '../types';
export default function FeatureSelection() {
  const {draft, pipeline} = useDraft(); const result = usePreview('/feature-selection/preview'); const p = draft.pipeline;
  return <><PageHeader eyebrow="04 / Feature selection" title="Select signal without leaking labels." description="Selection is performed inside each training pipeline. Preview scores are training-partition statistics, never holdout-derived rankings."/><DatasetPicker/><ErrorNotice message={result.error}/><Card title="Selection configuration"><div className="form-grid"><Field label="Method"><select value={p.selection} onChange={e => pipeline({selection: e.target.value as PipelineConfig['selection']})}><option value="none">No selection</option><option value="anova">ANOVA F score</option><option value="mutual_info">Mutual information</option><option value="variance">Variance threshold</option></select></Field><Field label="Maximum retained features" help="ANOVA / mutual information: capped at available encoded dimensions."><input type="number" min={1} max={400} value={p.k_features} onChange={e => pipeline({k_features: Number(e.target.value)})}/></Field><Field label="Variance threshold" help="Applied after the configured encoding and scaling stages."><input type="number" min={0} max={10} step="0.001" value={p.variance_threshold} onChange={e => pipeline({variance_threshold: Number(e.target.value)})}/></Field></div><Note>Selection scores are not medical feature importance. A feature selected on this benchmark does not establish biological causation.</Note><button disabled={!draft.dataset_id || result.busy} onClick={() => void result.refresh()}>{result.busy ? 'Calculating...' : 'Calculate training-only selection'}</button></Card>
    {result.preview && <div className="two-columns"><Card title="Training selection scores"><BarChart label="Training-only feature selection scores" items={result.preview.selection_scores.filter(s => s.score !== null).sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, 20).map(s => ({name: s.feature, value: s.score!}))}/></Card><Card title="Retained encoded features"><p>{result.preview.selected_features.length} features retained before PCA.</p><div className="chip-list">{result.preview.selected_features.map(f => <span className="chip" key={f}>{f}</span>)}</div><p>Fold-specific rankings may differ. The same procedure and partitions apply to all compared models.</p></Card></div>}</>;
}
