import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {Card, DatasetPicker, ErrorNotice, Field, JsonView, Note, PageHeader} from '../components/Common';
import {BarChart} from '../components/Charts';
import {metric} from '../utils/format';
export default function PCA() {
  const {draft, pipeline} = useDraft(); const result = usePreview('/pca/preview'); const p = draft.pipeline;
  return <><PageHeader eyebrow="05 / Dimensionality reduction" title="Fit the representation on training data." description="Reduce the selected feature space before classical and quantum learning. Held-out samples are transformed using the training-fitted representation."/><DatasetPicker/><ErrorNotice message={result.error}/>
    <Card title="PCA configuration"><div className="form-grid"><Field label="PCA components" help="For quantum comparisons this must equal the qubit count. Keep within training sample and selected feature dimensions."><input type="number" min={1} max={100} disabled={p.pca_components === null} value={p.pca_components ?? 4} onChange={e => pipeline({pca_components: Number(e.target.value)})}/></Field><label className="check"><input type="checkbox" checked={p.pca_components !== null} onChange={e => pipeline({pca_components: e.target.checked ? 4 : null})}/>Enable PCA</label><label className="check"><input type="checkbox" checked={p.pca_whiten} onChange={e => pipeline({pca_whiten: e.target.checked})}/>Whiten principal components</label></div><Note>Explained variance measures the fitted representation, not disease-prediction accuracy. Quantum and classical comparators share this representation.</Note><button disabled={!draft.dataset_id || result.busy} onClick={() => void result.refresh()}>{result.busy ? 'Fitting PCA...' : 'Calculate training-only PCA'}</button></Card>
    {result.preview && <Card title="Training representation"><p>Retained variance: <strong>{result.preview.pca_explained_variance.length ? metric(result.preview.pca_explained_variance.reduce((a, b) => a + b, 0)) : 'PCA disabled'}</strong></p><BarChart percent label="Training principal-component explained variance" items={result.preview.pca_explained_variance.map((value, index) => ({name: `PC${index + 1}`, value}))}/><JsonView value={{columns: result.preview.selected_features, loadings_by_component: result.preview.pca_loadings}} label="PCA component loadings"/><p className="mono wrap">Partition fingerprint: {result.preview.split_hash}</p></Card>}</>;
}
