import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {Card, DatasetPicker, ErrorNotice, Field, JsonView, Note, PageHeader, useActiveDataset} from '../components/Common';
import type {PipelineConfig} from '../types';
export default function Preprocessing() {
  const {draft, update, pipeline} = useDraft(); const dataset = useActiveDataset(); const result = usePreview(); const p = draft.pipeline;
  const features = dataset.data?.provenance.features || [], selected = draft.features || features, numeric = dataset.data?.provenance.numeric_features || [];
  function ratioField(index: number, key: 'name' | 'numerator' | 'denominator', value: string) {pipeline({ratios: p.ratios.map((r, i) => i === index ? {...r, [key]: value} : r)});}
  return <><PageHeader eyebrow="03 / Training-only transformations" title="Build a reproducible pipeline." description="All learned imputation, clipping, encoding and scaling parameters are fitted on training data only. Cross-validation fits fresh transformations in every fold."/><DatasetPicker/><ErrorNotice message={dataset.error || result.error}/>
    <div className="two-columns"><Card title="Input schema"><Field label="Selected input features" help="Target is excluded automatically. Exclude potential identifiers and target proxies."><select multiple size={12} value={selected} onChange={e => update({features: Array.from(e.target.selectedOptions, o => o.value)})}>{features.map(f => <option key={f} value={f}>{f}</option>)}</select></Field><button className="secondary" onClick={() => update({features: null})}>Use all non-target features</button><p>{selected.length} selected features. Target: {dataset.data?.provenance.target || 'Not selected'}.</p></Card>
    <Card title="Missing data, scaling and outliers"><div className="form-grid"><Field label="Numeric missing-value strategy"><select value={p.imputer} onChange={e => pipeline({imputer: e.target.value as PipelineConfig['imputer']})}><option value="median">Median</option><option value="mean">Mean</option><option value="most_frequent">Most frequent</option></select></Field><Field label="Scaling"><select value={p.scaler} onChange={e => pipeline({scaler: e.target.value as PipelineConfig['scaler']})}>{['standard', 'minmax', 'robust', 'none'].map(v => <option value={v} key={v}>{v}</option>)}</select></Field><Field label="Outlier strategy"><select value={p.outlier_strategy} onChange={e => pipeline({outlier_strategy: e.target.value as PipelineConfig['outlier_strategy']})}><option value="none">Retain observations</option><option value="clip_quantiles">Clip using training quantiles</option></select></Field><Field label="Duplicate records"><select value={draft.duplicate_policy} onChange={e => update({duplicate_policy: e.target.value as 'reject' | 'drop_exact'})}><option value="reject">Reject before split</option><option value="drop_exact">Explicitly drop exact duplicates</option></select></Field><Field label="Lower clipping quantile"><input type="number" min="0" max="0.49" step="0.01" value={p.lower_quantile} onChange={e => pipeline({lower_quantile: Number(e.target.value)})}/></Field><Field label="Upper clipping quantile"><input type="number" min="0.51" max="1" step="0.01" value={p.upper_quantile} onChange={e => pipeline({upper_quantile: Number(e.target.value)})}/></Field></div><Note>Categorical features use training-fitted most-frequent imputation and bounded one-hot encoding. Unseen categories are ignored by the encoder; this is not distribution-shift detection.</Note><label className="check"><input type="checkbox" checked={p.angle_scaling} onChange={e => pipeline({angle_scaling: e.target.checked})}/>Apply shared training-fitted angle scaling to [0, pi] for every compared model.</label></Card></div>
    <Card title="Feature engineering"><Field label="Optional log1p transforms" help="Select only nonnegative numeric features. Ratios are calculated on original values before log transforms."><select multiple size={5} value={p.log_features} onChange={e => pipeline({log_features: Array.from(e.target.selectedOptions, o => o.value)})}>{numeric.filter(f => selected.includes(f)).map(f => <option key={f} value={f}>{f}</option>)}</select></Field>{p.ratios.map((r, i) => <div className="ratio-row" key={i}><Field label="New feature name"><input value={r.name} onChange={e => ratioField(i, 'name', e.target.value)}/></Field>{(['numerator', 'denominator'] as const).map(key => <Field label={key} key={key}><select value={r[key]} onChange={e => ratioField(i, key, e.target.value)}><option value="">Select feature</option>{numeric.filter(f => selected.includes(f)).map(f => <option key={f} value={f}>{f}</option>)}</select></Field>)}<button className="ghost" onClick={() => pipeline({ratios: p.ratios.filter((_, j) => j !== i)})}>Remove</button></div>)}<button className="secondary" disabled={p.ratios.length >= 20} onClick={() => pipeline({ratios: [...p.ratios, {name: `ratio_${p.ratios.length + 1}`, numerator: '', denominator: ''}]})}>Add ratio feature</button></Card>
    <button disabled={result.busy || !draft.dataset_id} onClick={() => void result.refresh()}>{result.busy ? 'Fitting training-only preview...' : 'Preview training-only pipeline'}</button>{result.preview && <Card title="Fitted preview"><p>{result.preview.train_count} training / {result.preview.test_count} held-out samples / {result.preview.output_features.length} output dimensions</p><p className="workflow-ribbon">{result.preview.stages.join(' / ')}</p><JsonView value={result.preview} label="Preview metadata, selection scores and PCA loadings"/></Card>}</>;
}
