import {useEffect, useState} from 'react';
import {api} from '../services/api';
import {useAction} from '../hooks/useLoad';
import {useDraft} from '../hooks/ExperimentDraft';
import {Card, DatasetPicker, Empty, ErrorNotice, JsonView, Note, PageHeader, useActiveDataset} from '../components/Common';
import {BarChart} from '../components/Charts';
import type {Quality as QualityResult} from '../types';
export default function Quality() {
  const {draft} = useDraft(); const dataset = useActiveDataset(); const action = useAction(); const [checked, setChecked] = useState<QualityResult>();
  useEffect(() => setChecked(undefined), [draft.dataset_id, draft.features]);
  const quality = checked || dataset.data?.quality;
  async function validate() {const q = await action.run(() => api.post<QualityResult>(`/datasets/${draft.dataset_id}/validate`, {features: draft.features})); if (q) setChecked(q);}
  return <><PageHeader eyebrow="02 / Quality gates" title="Inspect before training." description="Review structure, target validity, class balance, duplicate records and potential leakage. Quality summaries contain aggregates, not raw records."/><DatasetPicker/><ErrorNotice message={dataset.error || action.error}/><button disabled={!draft.dataset_id || action.busy} onClick={() => void validate()}>{action.busy ? 'Checking...' : 'Validate selected input features'}</button>
    {quality ? <><div className="two-columns"><Card title="Class distribution"><BarChart label="Observed target class counts" items={Object.entries(quality.class_distribution).map(([name, value]) => ({name, value}))}/><p>{quality.row_count} source samples / {quality.feature_count} reviewed input features</p><p>{quality.class_imbalance ? 'Class imbalance detected.' : 'No class below the configured 20% minority threshold.'}</p></Card><Card title="Scientific quality gates">{quality.blockers.length ? quality.blockers.map(w => <ErrorNotice message={w} key={w}/>) : <Note>No blocking issue was found by these automated checks. This is not a guarantee of data suitability.</Note>}{quality.warnings.map(w => <p className="warning-text" key={w}>{w}</p>)}<p>Exact duplicate rows: <b>{quality.duplicate_rows}</b>. Duplicate feature vectors: <b>{quality.duplicate_feature_rows}</b>.</p></Card></div>
    <div className="two-columns"><Card title="Missing and infinite values"><div className="table-scroll"><table><thead><tr><th>Feature</th><th>Missing</th><th>Infinite</th></tr></thead><tbody>{Object.keys(quality.missing_values).map(name => <tr key={name}><td>{name}</td><td>{quality.missing_values[name]}</td><td>{quality.infinite_values[name] || 0}</td></tr>)}</tbody></table></div><p>{quality.invalid_numeric_values}</p></Card><Card title="Potential proxies and redundancy"><h3>Potential identifiers</h3><p>{quality.identifier_features.join(', ') || 'None detected by the name-based heuristic.'}</p><h3>Suspiciously predictive features</h3><p>{quality.suspiciously_predictive_features.join(', ') || 'None detected by the near-perfect target-proxy heuristic.'}</p><h3>Constant features</h3><p>{quality.constant_features.join(', ') || 'None detected.'}</p><JsonView value={quality.highly_correlated_pairs} label="Highly correlated feature pairs"/><JsonView value={quality.distributions} label="Aggregate feature distributions"/></Card></div></> : <Empty>Select a dataset to inspect its quality.</Empty>}</>;
}
