import {useState} from 'react';
import {Link} from 'react-router-dom';
import {api, notifyDataChanged} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import {useDraft} from '../hooks/ExperimentDraft';
import type {Job, Experiment, ModelKind, TrainingConfig} from '../types';
import {Card, DatasetPicker, Empty, ErrorNotice, Field, JsonView, Note, PageHeader, Status} from '../components/Common';
import QuantumSettings from '../components/QuantumSettings';
import {isActive, modelLabels, shortId} from '../utils/format';
export default function Training() {
  const {draft, update, pipeline} = useDraft(); const action = useAction(); const [created, setCreated] = useState<string>();
  const jobs = useLoad(() => api.get<Job[]>('/training/jobs'), [], 3000);
  const quantumSelected = draft.models.some(m => ['vqc', 'qsvc'].includes(m));
  function toggle(kind: ModelKind) {
    const models = draft.models.includes(kind) ? draft.models.filter(m => m !== kind) : [...draft.models, kind];
    update({models, ...(models.some(m => ['vqc', 'qsvc'].includes(m)) ? {calibration: 'none', parameters: {...draft.parameters, class_weight: null}} : {})});
    if (models.some(m => ['vqc', 'qsvc'].includes(m))) pipeline({pca_components: draft.quantum.qubits, angle_scaling: true});
  }
  async function train() {const value = await action.run(() => api.post<{job: Job; experiment: Experiment}>('/training/jobs', draft)); if (value) {setCreated(value.experiment.id); notifyDataChanged();}}
  return <><PageHeader eyebrow="06 / Execution and evaluation" title="Run a controlled comparison." description="One experiment defines the shared dataset, subset, split and transformations. Every model receives the same training and held-out samples."/><DatasetPicker/><ErrorNotice message={action.error || jobs.error}/>
    <Card title="Classical and quantum models"><div className="model-options">{(Object.keys(modelLabels) as ModelKind[]).map(kind => <label className={`model-option ${draft.models.includes(kind) ? 'chosen' : ''}`} key={kind}><input type="checkbox" checked={draft.models.includes(kind)} onChange={() => toggle(kind)}/><strong>{modelLabels[kind]}</strong><small>{['vqc', 'qsvc'].includes(kind) ? 'Quantum simulation' : 'Classical baseline'}</small></label>)}</div><Note>Quantum comparisons default to four PCA components and a common stratified subset of up to 160 samples. Subsampling applies to every model, not only quantum models; it limits runtime, not scientific uncertainty.</Note></Card>
    <div className="two-columns"><Card title="Partitions and evaluation"><div className="form-grid"><Field label="Random seed"><input type="number" min={0} value={draft.seed} onChange={e => update({seed: Number(e.target.value)})}/></Field><Field label="Held-out test fraction"><input type="number" min={0.1} max={0.4} step={0.05} value={draft.test_size} onChange={e => update({test_size: Number(e.target.value)})}/></Field><Field label="Stratified CV folds"><input type="number" min={2} max={10} value={draft.cv_folds} onChange={e => update({cv_folds: Number(e.target.value)})}/></Field><Field label="Common maximum sample count" help="Leave empty for all samples. Quantum runs must fit the server sample budget."><input type="number" min={30} max={100000} value={draft.max_samples ?? ''} onChange={e => update({max_samples: e.target.value ? Number(e.target.value) : null})}/></Field><Field label="Model probability decision threshold" help="Fixed before training; margin-only SVM/QSVC use a zero decision-score cutoff."><input type="number" min={0.01} max={0.99} step={0.01} value={draft.probability_threshold} onChange={e => update({probability_threshold: Number(e.target.value)})}/></Field><Field label="Probability calibration" help="Classical-only, inner CV around the entire pipeline; never clinical validation."><select disabled={quantumSelected} value={draft.calibration} onChange={e => update({calibration: e.target.value as TrainingConfig['calibration']})}><option value="none">None</option><option value="sigmoid">Sigmoid / Platt</option><option value="isotonic">Isotonic</option></select></Field><Field label="Inner calibration folds"><input type="number" min={2} max={5} disabled={draft.calibration === 'none'} value={draft.calibration_folds} onChange={e => update({calibration_folds: Number(e.target.value)})}/></Field></div></Card>
    <Card title="Classical model configuration"><div className="form-grid"><Field label="Logistic regression C"><input type="number" min={0.001} step={0.1} value={draft.parameters.logistic_c} onChange={e => update({parameters: {...draft.parameters, logistic_c: Number(e.target.value)}})}/></Field><Field label="SVM / QSVC C"><input type="number" min={0.001} step={0.1} value={draft.parameters.svm_c} onChange={e => update({parameters: {...draft.parameters, svm_c: Number(e.target.value)}})}/></Field><Field label="SVM kernel"><select value={draft.parameters.svm_kernel} onChange={e => update({parameters: {...draft.parameters, svm_kernel: e.target.value as 'linear' | 'rbf'}})}><option value="rbf">RBF</option><option value="linear">Linear</option></select></Field><Field label="Random forest trees"><input type="number" min={10} max={500} value={draft.parameters.forest_trees} onChange={e => update({parameters: {...draft.parameters, forest_trees: Number(e.target.value)}})}/></Field><Field label="Forest maximum depth" help="Empty means unrestricted tree depth."><input type="number" min={1} max={100} value={draft.parameters.forest_max_depth ?? ''} onChange={e => update({parameters: {...draft.parameters, forest_max_depth: e.target.value ? Number(e.target.value) : null}})}/></Field><Field label="Class weighting"><select disabled={quantumSelected} value={draft.parameters.class_weight || 'none'} onChange={e => update({parameters: {...draft.parameters, class_weight: e.target.value === 'balanced' ? 'balanced' : null}})}><option value="none">None (required for VQC comparison)</option><option value="balanced">Balanced</option></select></Field></div></Card></div>
    <Card title="Quantum configuration"><QuantumSettings/></Card><JsonView value={draft} label="Exact configuration to persist"/><div className="action-bar"><button disabled={action.busy || !draft.dataset_id || !draft.models.length} onClick={() => void train()}>{action.busy ? 'Creating job...' : 'Create training experiment'}</button>{created && <Link className="text-link" to={`/experiments/${created}`}>Open experiment {shortId(created)}</Link>}</div>
    <Card title="Background jobs">{jobs.data?.length ? jobs.data.map(job => <div className="job-card" key={job.id}><div className="spread"><Link to={`/experiments/${job.experiment_id}`}>Experiment {shortId(job.experiment_id)}</Link><Status value={job.status}/></div><p>{job.state}</p><progress max={100} value={job.progress}/><small>Stage-based progress: {job.progress}%. It is not an estimate of optimizer convergence or remaining time.</small>{isActive(job.status) && <button className="secondary" disabled={action.busy} onClick={() => void action.run(async () => {await api.post(`/training/jobs/${job.id}/cancel`); jobs.reload();})}>Request cancellation</button>}{job.errors.length > 0 && <JsonView value={job.errors} label="Recorded model failures"/>}</div>) : <Empty>No jobs have been submitted.</Empty>}</Card></>;
}
